//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 02:16:09 PM GMT+01:00 
//


package com.vincedgy.jsf2project.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ville" type="{http://jad.orsys.fr/exercice10}ville" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="mode-de-Transport" type="{http://jad.orsys.fr/exercice10}mode-de-transport" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ville",
    "modeDeTransport"
})
@XmlRootElement(name = "agence-voyages")
public class AgenceVoyages implements Serializable {

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "ville")
    protected List<Ville> ville;
    @XmlElement(name = "mode-de-Transport")
    protected List<ModeDeTransport> modeDeTransport;

    /**
     * Gets the value of the ville property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ville property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVille().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ville }
     * 
     * 
     */
    public List<Ville> getVille() {
        if (ville == null) {
            ville = new ArrayList<Ville>();
        }
        return this.ville;
    }

    /**
     * Gets the value of the modeDeTransport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modeDeTransport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModeDeTransport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModeDeTransport }
     * 
     * 
     */
    public List<ModeDeTransport> getModeDeTransport() {
        if (modeDeTransport == null) {
            modeDeTransport = new ArrayList<ModeDeTransport>();
        }
        return this.modeDeTransport;
    }

}
